version: '3.4'

x-tests-template: &tests-template
    image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:40-${CI_IMAGE_VERSION:-latest}
    command: tox -vvvvv -- --color=yes --integration
    environment:
      TOXENV: ${CI_TOXENV_ALL}

    # Enable privileges to run the sandbox
    #
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse

    # Mount the local directory and set the working directory
    # to run the tests from.
    #
    volumes:
      - ../..:/home/testuser/buildstream
    working_dir: /home/testuser/buildstream


services:

  debian-11:
    <<: *tests-template
    image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-debian:11-${CI_IMAGE_VERSION:-latest}

  fedora-40:
    <<: *tests-template
    image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:40-${CI_IMAGE_VERSION:-latest}

  ubuntu-22.04:
    <<: *tests-template
    image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-ubuntu:22.04-${CI_IMAGE_VERSION:-latest}

  # Ensure that tests also pass in the absence of a sandboxing tool
  fedora-missing-deps:
    <<: *tests-template
    image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:minimal-${CI_IMAGE_VERSION:-latest}

  # Test against the master version of BuildStream
  bst-master:
    <<: *tests-template
    environment:
      TOXENV: ${CI_TOXENV_MASTER}

  docs:
    <<: *tests-template
    command: tox -e docs

  lint:
    <<: *tests-template
    command: tox -e lint,format-check

  mypy:
    <<: *tests-template
    command: tox -e mypy
